### ISSUE TITLE
ModelAndView status enum displays duplicate values

### ISSUE THREAD

**Issue by apixandru** [springfox/springfox#1485]
One of the reasons why the generated api-docs doesn't work in the swagger editor is the HttpStatus enum. 

```
status:
        type: "string"
        enum:
[...]
        - "300"
        - "301"
        - "302"
        - "302" <-- duplicate
        - "303"
[...]
        - "410"
        - "411"
        - "412"
        - "413"
        - "413" <-- duplicate
        - "414"
```
