### ISSUE TITLE
@EnableSwagger2 cause the microservice could not be accessed

### ISSUE THREAD

**Issue by GreatJohnny** [springfox/springfox#1673]
Hi:
I implement a microservice demo  with spring cloud, everything  works fine. but when add @EnableSwagger2 on a service. And it registered with Eureka successfully. But when a @FeignClient access the service . The exception occured:
```
2017-02-13 09:36:00.663  INFO 8840 --- [-hbca-service-1] c.n.l.DynamicServerListLoadBalancer      : DynamicServerListLoadBalancer for client hbca-service initialized: DynamicServerListLoadBalancer:{NFLoadBalancer:name=hbca-service,current list of Servers=[],Load balancer stats=Zone stats: {},Server stats: []}ServerList:org.springframework.cloud.netflix.ribbon.eureka.DomainExtractingServerList@bf8e220
2017-02-13 09:36:00.727 ERROR 8840 --- [nio-3333-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is com.netflix.hystrix.exception.HystrixRuntimeException: SalesProxy#index() failed and no fallback available.] with root cause

com.netflix.client.ClientException: Load balancer does not have available server for client: hbca-service
	at com.netflix.loadbalancer.LoadBalancerContext.getServerFromLoadBalancer(LoadBalancerContext.java:483) ~[ribbon-loadbalancer-2.2.2.jar:2.2.2]
...
```
This is the build.gradle of EurekaServer :

```
buildscript {
	ext {
		springBootVersion = '1.5.1.RELEASE'
	}
	...
	dependencies {
		classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")
	}
}
...
dependencies {
	compile('org.springframework.cloud:spring-cloud-starter-eureka-server')
	testCompile('org.springframework.boot:spring-boot-starter-test')
}

dependencyManagement {
	imports {
		mavenBom "org.springframework.cloud:spring-cloud-dependencies:Dalston.M1"
	}
}
```
the application.yml of EurekaServer:
```
server:
  port: 1111

spring:
  application:
    name: eurekaserver

eureka:
  instance:
    hostname: localhost
    preferIpAddress: true   
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
```
---------------------------------------------------------
THe build.gradle of HBService:
```
buildscript {
	ext {
		springBootVersion = '1.5.1.RELEASE'
	}
	...
	dependencies {
		classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")
	}
}
...
dependencies {
	compile('org.springframework.boot:spring-boot-starter-web')
	compile('org.springframework.cloud:spring-cloud-starter-feign')
	compile('org.springframework.cloud:spring-cloud-starter-eureka')
	
	compile "io.springfox:springfox-swagger2:2.6.1"
	compile 'io.springfox:springfox-swagger-ui:2.6.1'
	
	testCompile('org.springframework.boot:spring-boot-starter-test')
}

dependencyManagement {
	imports {
		mavenBom "org.springframework.cloud:spring-cloud-dependencies:Camden.RELEASE"
	}
}
```
the applcation.yml of HBService:
```
server:
  port: 8081
  contextPath: /hbca
spring:
  application:
    name: hbca-service
     
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:1111/eureka/
  instance: 
    healthCheckUrlPath: ${management.context-path}/health 
    appname: hbca-service
```
----------------------------------------------------------------
The build.gradle of client:
```
buildscript {
	ext {
		springBootVersion = '1.5.1.RELEASE'
	}
	...
	dependencies {
		classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")
	}
}
...
dependencies {
	compile('org.springframework.boot:spring-boot-starter-web')
	compile('org.springframework.cloud:spring-cloud-starter-eureka')
	compile('org.springframework.cloud:spring-cloud-starter-feign')
	
	testCompile('org.springframework.boot:spring-boot-starter-test')
}

dependencyManagement {
	imports {
		mavenBom "org.springframework.cloud:spring-cloud-dependencies:Dalston.M1"
	}
}
```
the application.yml of client:
```
server:
  port: 3333
   
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
  instance:
    preferIpAddress: true
```
-----------------------------------------------------------
Here is the demo.[SpringCloudTest.zip](https://github.com/springfox/springfox/files/769916/SpringCloudTest.zip)

Thanks!
