### ISSUE TITLE
collectionFormat problem

### ISSUE THREAD

**Issue by vitek499** [springfox/springfox#1946]
I woud like to generate this:
```
  '/yyy':
    get:
      parameters:
        - name: states
          in: query
          description: xxxxxxx
          required: false
          type: array
          items:
            type: string
            enum:
              - check
              - closed
          collectionFormat: csv
```

I use `@ApiImplicitParam` annotation, like this:
```
 @ApiImplicitParam(name = "states", allowMultiple = true, paramType = "query", collectionFormat = "csv", allowableValues = "check, closed")
```

but everytime, its generate with `collectionFormat: multi`.

Thanks for your advice
