### ISSUE TITLE
Schema error: path parameters should not have additional property allowEmptyValue

### ISSUE THREAD

**Issue by agusevas** [springfox/springfox#2419]
- [x] What version of the library are you using? 
2.9

What kind of issue is this?
 - [x ] Bug report. 
The online Swagger editor shows the following errors:

> Schema error at paths['/cart/coupons/{couponId}'].delete.parameters[0]
> should NOT have additional properties
> additionalProperty: type, allowEmptyValue, format, name, in, description, required

Generated Swagger definition:
```
parameters:
        - name: couponId
          in: path
          description: The coupon id
          required: true
          type: string
          allowEmptyValue: false
          format: uuid
```

The Java code:
```
@DeleteMapping("/coupons/{couponId}")
public CartTO deleteCoupon(@PathVariable @ApiParam(value = "The coupon id", required = true) UUID couponId) {
        return cartService.deleteCoupon(couponId);
    }
```

according to the Swagger Specification the `allowEmptyValue` should be generated only for `query` or `formData` parameters. See https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#parameterObject for more information.
