### ISSUE TITLE
Path Parameter generated having unsupported properties 

### ISSUE THREAD

**Issue by FossilBlade** [springfox/springfox#2498]
Version - 2.9.0

Reporting a Bug.

Hi,

With the Spring framework annotation PathVariable the api-doc which is getting created, does not have the "required" property set to true. Also unsupported property "allowEmptyValue" is being set with this.

With the following code:

```java
@RequestMapping(method = RequestMethod.GET, path = "/{id}", produces = "application/json")  
@ApiOperation(value="Test Get Person", response=Person.class)
public Person getPersonById(@ApiParam(value="Id of the Person") @PathVariable int id) {
        return personService.getPersonById(id);
    }
```

The swagger definition being generated is:
```yaml
'/v1/api/persons/{id}':
    get:
      tags:
        - personController
           summary: Test Get Person
      operationId: getPersonByIdUsingGET
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: Id of the Person
          required: false
          type: integer
          allowEmptyValue: false
          format: int32
```

As per the Swagger version 2.0 documentation if the Parameter is of type path then the required property should always be true and "allowEmptyValue" should not be present.
