### ISSUE TITLE
request-body Object Payload

### ISSUE THREAD

**Issue by eduardocintra** [springfox/springfox#2768]
How can I reproduce the follwing OpenApi using springfox-swagger2?
```
      parameters:
      - in: body
        name: user
        description: The user to create.
        schema:
          type: object
          required:
            - userName
          properties:
            userName:
              type: string
            firstName:
              type: string
            lastName:
              type: string	
```

Here it describes this:
https://swagger.io/docs/specification/2-0/describing-request-body/
