### ISSUE TITLE
RequestParam incorrectly rendered as formData when together with a MultipartFile

### ISSUE THREAD

**Issue by gionn** [springfox/springfox#2950]
Springfox 2.9.2, a controller with:

```java
    public VirtualMachineConfigurationDTO parseDockerCompose(
            @ApiParam( required = true ) MultipartFile file,
            @RequestParam( value = "version", defaultValue = "0.0.1" ) String version,
            @PathVariable int id ) 
```

get rendered as:

```yaml
  summary: Update a VirtualMachineConfiguration by parsing a docker-compose file
  operationId: virtualMachineConfigurationParseDockerCompose
  consumes:
    - multipart/form-data
  parameters:
    - name: file
      in: formData
      description: file
      required: true
      type: file
    - name: id
      in: path
      description: id
      required: true
      type: integer
      format: int32
    - in: formData
      name: version
      description: version
      required: false
      schema:
        type: string
```

But version is not a formData field but a query param.
