### ISSUE TITLE
How to generate RequestBody with type 'Object' and properties using Springfox

### ISSUE THREAD

**Issue by vaibhavn** [springfox/springfox#3011]
- [ ] Springfox version: 2.9.2

 - [ ] Question. How to generate swagger json in following format? I could not find any Java example file to refer to for same.
What are annotations need to be used in Java class to generate JSON in following format:
```yaml
          {
            "in": "body",
            "name": "body",
            "description": "Testing",
            "required": false,
            "schema": {
              "type": "object",
              "properties": {
                "contextData":  {
                  "$ref": "#/definitions/ContextData"
                },
                "name": {
                  "type": "string"
                },
                "startImmediately" :{
                    "type": "boolean"
                }
              }
            }
          }
```

For more information:
(https://github.com/swagger-api/swagger-editor/issues/1992)
