### ISSUE TITLE
SpringFox incorrectly produces string instead of array

### ISSUE THREAD

**Issue by gmarchelos** [springfox/springfox#3041]
Having this function

```kotlin
@RequestMapping(method = [RequestMethod.GET], value = ["/test"])
fun test(@RequestParam(defaultValue = "a,b") list: List<String>) {}
```

And swagger produces this **actual output**

```
- name: list
  in: query
  description: list
  required: false
  type: array
  items:
    type: string
  collectionFormat: multi
  default: 'a,b'
```

**Expected output**
```
- name: list
  in: query
  description: list
  required: false
  type: array
  items:
    type: string
  collectionFormat: multi
  default: [a,b]
```

**Dependencies**
```
implementation("io.springfox:springfox-swagger2:3.0.0-SNAPSHOT")
implementation("io.springfox:springfox-swagger-ui:3.0.0-SNAPSHOT")
implementation("io.springfox:springfox-spring-webflux:3.0.0-SNAPSHOT")
```
