### ISSUE TITLE
Discriminator without attribute with @JsonTypeInfo

### ISSUE THREAD

**Issue by Frrede** [springfox/springfox#3236]
I maybe faced a bug in Version 2.9.2 when using jacksons `JsonTypeInfo` and `JsonSubTypes` annotation. Here is an example:
```
@JsonTypeInfo(
    use = JsonTypeInfo.Id.NAME,
    property = "shape")
@JsonSubTypes({
    @JsonSubTypes.Type(value = Car.class, name = "CAR"),
    @JsonSubTypes.Type(value = Bicycle.class, name = "BICYCLE")
})
public class Vehicle {
}
```
The generated swagger looks like that:
```
Vehicle:
  type: object
  discriminator: shape
  title: Vehicle
```
When generating code with the swagger with swagger-codegen-cli.jar it assumes that there's a property "shape" and the project can't be build.

So is it possible, that the swagger isn't valid with the descriminator "shape" without a property "shape"?
(I now I could add the property "shape" to the class but that results in two json attributes "shape"...)

swagger-codegen-cli would work correctly when fixing the swagger like that:
```
Vehicle:
  type: object
  discriminator: shape
  properties:
    shape:
      type: string
  title: Vehicle
```
