### ISSUE TITLE
Spring Data REST EntityModel contains "links" property instead of "_links"

### ISSUE THREAD

**Issue by twobiers** [springfox/springfox#3649]
Please take the time to search the repository, if your question has already been asked or answered.

- [x] What version of the library are you using? Is it the latest version? The latest released version is [ ![Download](https://api.bintray.com/packages/springfox/maven-repo/springfox/images/download.svg) ](https://bintray.com/springfox/maven-repo/springfox/_latestVersion)

```xml
<dependency>
      <groupId>io.springfox</groupId>
      <artifactId>springfox-boot-starter</artifactId>
      <version>3.0.0</version>
    </dependency>
```

What kind of issue is this?
 - [x] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests or 
       steps to reproduce get fixed faster. Here’s an example: https://gist.github.com/swankjesse/6608b4713ad80988cdc9
    - [x] spring xml/java config that is relevant
    - [x] springfox specific configuration if it makes sense
    - [x] include any output you've received; logs, json snippets etc.; and what the expected output should be
    - [x] if you have a repo that demonstrates the issue for bonus points! See [this example](https://github.com/springfox/springfox/issues/494) 

Please do consider ***starring*** this repository if you do like this project and find it useful. 

Configuration is as simple as this:
```java
@Bean
public Docket api() {
  return new Docket(DocumentationType.OAS_30)
      .forCodeGeneration(true)
      .select()
      .apis(RequestHandlerSelectors.any())
      .paths(PathSelectors.ant("/foo/**").or(PathSelectors.ant("/bar/**")))
      .build();
}
```

When exposing a Spring DATA REST Repository springfox generates two schemas which contain HAL links, `CollectionOfFoo` and `EntityModelOfFoo`. The CollectionModel is correctly formed as the following:
```yml
CollectionModelOfFoo:
  title: CollectionModelOfFoo
  required:
  - _embedded
  - _links
  type: object
  properties:
    _embedded:
      "$ref": "#/components/schemas/EmbeddedCollectionOfFoo"
    _links:
      type: object
      additionalProperties:
        "$ref": "#/components/schemas/Link"
      description: Link collection
```

however the EntityModel is defining a `links` section instead of a `_links` section:

```yml
EntityModelOfFoo:
  title: EntityModelOfFoo
  type: object
    properties:
      links:
        "$ref": "#/components/schemas/Links"
```

Here is a Repository which produces this: https://github.com/tobi6112/springfox-hal-links-issue
