### ISSUE TITLE
[BUG] context path and servlet path are reversed in /v2/api-docs

### ISSUE THREAD

**Issue by gbaso** [springfox/springfox#3755]
I'm using springfox-boot-starter 3.0.0 with spring boot 2.4.3, both latest versions as of now.

In my `application.yml` I have the path configuration:
```yml
server:
  servlet:
    context-path: /my-context-path
spring:
  mvc:
    servlet:
      path: /api
```
so that my controllers are exposed to `my-host/my-context-path/api/<controller-path>`.

However, swagger has the paths reversed:
```json
{
    "swagger": "2.0",
    "info": {
        "description": "My App REST API",
        "title": "My App"
    },
    "host": "my-host",
    "basePath": "/api",
    "tags": [...],
    "paths": {
        "/my-context-path/<controller-path>/<mapping>": {...}
    },
    "definitions": {...}
}
```

resulting in a 404 error when using the "try it out" feature, since `my-host/api/my-context-path/<controller-path>/<mapping>` does not exists.

Minimal example to reproduce: https://github.com/gbaso/swagger-path
