### ISSUE TITLE
Aggregate  API Docs in Spring Gateway failed

### ISSUE THREAD

**Issue by hantsy** [springfox/springfox#3897]
Please take the time to search the repository, if your question has already been asked or answered.

- [x] What version of the library are you using? 
3.0.0

What kind of issue is this?

- [x] Bug report. If you’ve found a bug, spend the time to write a failing test. 

The reproducer codes: https://github.com/hantsy/spring-puzzles/blob/master/springfox-gateway/
     
I tried to add an aggregated Swagger UI for all downstream service in a Microservices architecture, but failed.

```java 
    @Primary
    @Bean
    public SwaggerResourcesProvider swaggerResourcesProvider(InMemorySwaggerResourcesProvider defaultResourcesProvider) {
        return () -> {
            SwaggerResource customersResource = new SwaggerResource();
            customersResource.setName("Customers Endpoints");
            customersResource.setSwaggerVersion("3.0");

            customersResource.setUrl("/customers/v3/api-docs");
            //customersResource.setUrl("http://localhost:8001/v3/api-docs");

            SwaggerResource ordersResource = new SwaggerResource();
            ordersResource.setName("Orders Endpoints");
            ordersResource.setSwaggerVersion("3.0");
            ordersResource.setUrl("/orders/v3/api-docs");
            //ordersResource.setUrl("http://localhost:8002/v3/api-docs");

            List<SwaggerResource> resources = new ArrayList<>(defaultResourcesProvider.get());
            resources.add(customersResource);
            resources.add(ordersResource);
            return resources;
        };
    }
```

The router config in the gateway application.yml is similar to this.

```yml

spring:
  cloud:
    gateway:
      routes:
        - id: customers
          uri: http://localhost:8001
          predicates:
            - Path=/customers/**
          filters:
            - RewritePath=/customers/(?<segment>.*), /$\{segment}
        - id: orders
          uri: http://localhost:8002
          predicates:
            - Path=/orders/**
          filters:
            - RewritePath=/orders/(?<segment>.*), /$\{segment}
```

The swagger resources url added the gateway URL by default, I can not set a full URL with HTTP/HTTPS protocol. 

When running the application, the Swagger UI is displayed, but when I tried to run the endpoints in the downstream service(eg. hosted on http://localhost:8001), it always called on the gateway host(hosted on http://localhost:8080), it is incorrect.

**Excepted**:  If it called on http://localhost:8080/customers, it will work due to rewrite rules, but it seems there is no way to set up the rewrite rules.  Or called on the target host address: http://localhost:8001.
