### ISSUE TITLE
Is it possible to have a multiple YAML doc files for each controller or endpoint?

### ISSUE THREAD

**Issue by shahlin-bsfdv** [springfox/springfox#4036]
What kind of issue is this?
 - [x] Question. Is this a question about how to do a certain thing? 

**Question**: I would like to have multiple YAML files for each controller or even an endpoint where all the Swagger documentation is present. So the controller is not polluted with all the documentation code. Is this possible?

**Example**:
Controller level docs
```kotlin
@ApiDocumentation("/swagger-docs/users/userController.yaml")
class UserController {
    @GetMapping
    fun getUser(@RequestBody request: UserRequest): ResponseEntity {
        // ...
    }

    @PostMapping
    fun createUser(@RequestBody request: UserRequest): ResponseEntity {
        // ...
    }
}
```

Endpoint level docs
```kotlin
class UserController {
    @GetMapping
    @ApiDocumentation("/swagger-docs/users/getUser.yaml")
    fun getUser(@RequestBody request: UserRequest): ResponseEntity {
        // ...
    }

    @PostMapping
    @ApiDocumentation("/swagger-docs/users/createUser.yaml")
    fun createUser(@RequestBody request: UserRequest): ResponseEntity {
        // ...
    }
}
```

YAML sample for `/swagger-docs/users/userController.yaml`:
```yaml
schemes:
  - "https"
  - "http"
paths:
  /users:
    get:
      tags:
        - "user"
      summary: "Get all users"
      description: ""
      ...
    post:
      ...
```

Thanks!
